import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/src/components/NavBar'
import Footer from '@/src/components/footer'
import {Inter, Libre_Caslon_Text} from '@next/font/google'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})
const lctext = Libre_Caslon_Text({
  weight: ["400" , "700"],
  variable: '--font-librecaslontext',
  subsets: ['latin'],

})

import localFont from '@next/font/local';
const CalistoMT = localFont({
  src: '../../font/calist.ttf',
  variable: '--font-CalistoMT',

  })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  

  return (
    <html lang="en">
      <body>
        <main className={`${inter.variable} ${lctext.variable} ${CalistoMT.variable} font-sans`}>
        <NavBar />
          {children}
        <Footer />
        </main>
      </body>
    </html>
  )
}

